# Generated by Django 5.2.5 on 2025-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('carteirinha', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
