# Generated by Django 5.2.5 on 2025-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código do procedimento')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('IMG', 'Exame de Imagem'), ('LAB', 'Exame Laboratorial'), ('CON', 'Consulta Médica'), ('TER', 'Terapia'), ('OUT', 'Outro')], max_length=3, verbose_name='Categoria')),
            ],
        ),
    ]
