# Generated by Django 5.2.5 on 2025-08-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0002_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cbo', models.CharField(max_length=25, verbose_name='Código CBO')),
                ('titulo_cbo', models.CharField(max_length=200, verbose_name='Título CBO')),
            ],
        ),
        migrations.CreateModel(
            name='Executante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='categoria',
            field=models.CharField(choices=[('IMG', 'Exame de Imagem'), ('LAB', 'Exame Laboratorial'), ('CON', 'Consulta Médica'), ('TER', 'Terapia'), ('PQN', 'Pequena Cirurgia'), ('OUT', 'Outro')], max_length=3, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='ProfissionalSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=100, verbose_name='Nome do Profissional Solicitante')),
                ('conselho', models.CharField(choices=[('CRM', 'CRM'), ('CRP', 'CRP'), ('CRO', 'CRO'), ('CRN', 'COREN')], max_length=3, verbose_name='Conselho do Profissional')),
                ('UF_Conselho', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF do Conselho')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código do Profissional Solicitante')),
                ('cbos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorNet_app.cbos')),
            ],
        ),
    ]
