# Generated by Django 5.2.5 on 2025-08-23 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0003_cbos_executante_alter_procedimento_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbos',
            name='codigo_cbo',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código CBO'),
        ),
        migrations.AlterField(
            model_name='cbos',
            name='titulo_cbo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título CBO'),
        ),
        migrations.AlterField(
            model_name='profissionalsolicitante',
            name='cbos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DoctorNet_app.cbos'),
        ),
        migrations.AlterField(
            model_name='profissionalsolicitante',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código do Profissional Solicitante'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carater_solicitacao', models.CharField(choices=[('URG', 'Urgência'), ('ELE', 'Eletivo')], max_length=3, verbose_name='Caráter de Solicitação')),
                ('status', models.CharField(choices=[('APV', 'Pedido Aprovado'), ('ANA', 'Em Análise'), ('PEN', 'Pendência')], max_length=3, verbose_name='Status do Pedido')),
                ('credenciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('executante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DoctorNet_app.executante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DoctorNet_app.beneficiario')),
                ('procedimento_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DoctorNet_app.procedimento')),
                ('profissional_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DoctorNet_app.profissionalsolicitante')),
            ],
        ),
    ]
