# Generated by Django 5.2.5 on 2025-08-24 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0004_alter_cbos_codigo_cbo_alter_cbos_titulo_cbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
