# Generated by Django 5.2.5 on 2025-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0005_solicitacao_data_solicitacao_solicitacao_numero_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='executante',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
