# Generated by Django 5.2.5 on 2025-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0006_executante_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='codigo',
            new_name='codigo_procedimento',
        ),
        migrations.RenameField(
            model_name='profissionalsolicitante',
            old_name='conselho',
            new_name='tipo_conselho',
        ),
        migrations.AlterField(
            model_name='executante',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
    ]
