# Generated by Django 5.2.5 on 2025-08-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0007_rename_codigo_procedimento_codigo_procedimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='procedimento_solicitado',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='quantidade_procedimento',
            field=models.CharField(default=0, max_length=2, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorNet_app.procedimento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='DoctorNet_app.solicitacao')),
            ],
        ),
    ]
