# Generated by Django 5.2.5 on 2025-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0008_remove_solicitacao_procedimento_solicitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='indicacao',
            field=models.CharField(default=0, max_length=500, verbose_name='Indicação Clínica'),
            preserve_default=False,
        ),
    ]
