# Generated by Django 5.2.5 on 2025-08-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0009_solicitacao_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(upload_to='anexoautorizacao/')),
            ],
        ),
    ]
