# Generated by Django 5.2.6 on 2025-09-17 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0010_anexosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DoctorNet_app.solicitacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('APV', 'Pedido Aprovado'), ('ANA', 'Em Análise'), ('PEN', 'Pendência'), ('NEV', 'Negado')], max_length=3, verbose_name='Status do Pedido'),
        ),
    ]
