# Generated by Django 5.2.6 on 2025-09-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorNet_app', '0011_anexosolicitacao_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='anexo',
            field=models.FileField(upload_to='solicitacoes/anexos/%Y/%m/%d/'),
        ),
    ]
